/*
 * Copyright (c) 2010 by Guido Steinacker
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.23 at 02:24:22 PM MEZ 
//


package de.steinacker.jcg.transform.translation.binding;

import javax.annotation.Generated;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pluralTerm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="translation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pluralTranslation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shortDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="longDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "term",
        "pluralTerm",
        "translation",
        "pluralTranslation",
        "shortDescription",
        "longDescription"
})
@XmlRootElement(name = "entry")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class Entry {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String term;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String pluralTerm;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String translation;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String pluralTranslation;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String shortDescription;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String longDescription;

    /**
     * Gets the value of the term property.
     *
     * @return possible object is
     *         {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setTerm(String value) {
        this.term = value;
    }

    /**
     * Gets the value of the pluralTerm property.
     *
     * @return possible object is
     *         {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getPluralTerm() {
        return pluralTerm;
    }

    /**
     * Sets the value of the pluralTerm property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setPluralTerm(String value) {
        this.pluralTerm = value;
    }

    /**
     * Gets the value of the translation property.
     *
     * @return possible object is
     *         {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getTranslation() {
        return translation;
    }

    /**
     * Sets the value of the translation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setTranslation(String value) {
        this.translation = value;
    }

    /**
     * Gets the value of the pluralTranslation property.
     *
     * @return possible object is
     *         {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getPluralTranslation() {
        return pluralTranslation;
    }

    /**
     * Sets the value of the pluralTranslation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setPluralTranslation(String value) {
        this.pluralTranslation = value;
    }

    /**
     * Gets the value of the shortDescription property.
     *
     * @return possible object is
     *         {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Gets the value of the longDescription property.
     *
     * @return possible object is
     *         {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getLongDescription() {
        return longDescription;
    }

    /**
     * Sets the value of the longDescription property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setLongDescription(String value) {
        this.longDescription = value;
    }

}
