/*
 * Copyright (c) 2010 by Guido Steinacker
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.23 at 02:24:22 PM MEZ 
//


package de.steinacker.jcg.transform.translation.binding;

import javax.annotation.Generated;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}language"/>
 *         &lt;element ref="{}entry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "language",
        "entry"
})
@XmlRootElement(name = "glossary")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class Glossary {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected Language language;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected List<Entry> entry;

    /**
     * Gets the value of the language property.
     *
     * @return possible object is
     *         {@link Language }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public Language getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     *
     * @param value allowed object is
     *              {@link Language }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setLanguage(Language value) {
        this.language = value;
    }

    /**
     * Gets the value of the entry property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>setParameters</CODE> method for the entry property.
     * <p/>
     * <p/>
     * For example, to addParameter a new item, do as follows:
     * <pre>
     *    getEntry().addParameter(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Entry }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public List<Entry> getEntry() {
        if (entry == null) {
            entry = new ArrayList<Entry>();
        }
        return this.entry;
    }

}
