/*
 * Copyright (c) 2010 by Guido Steinacker
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.23 at 02:24:22 PM MEZ 
//


package de.steinacker.jcg.transform.translation.binding;

import javax.annotation.Generated;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}language" />
 *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}language" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "language")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class Language {

    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String source;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String target;

    /**
     * Gets the value of the source property.
     *
     * @return possible object is
     *         {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the target property.
     *
     * @return possible object is
     *         {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-03-23T02:24:22+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setTarget(String value) {
        this.target = value;
    }

}
